// Package index renders the generated table of every decision in a corpus.
//
// The index is a build artifact that gets committed, so it is verified rather
// than pushed: `jerry index --check` fails when the tracked file disagrees
// with the documents. That avoids a CI bot pushing to a protected branch and
// the non-fast-forward failures two close merges cause.
package index

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"path"
	"sort"
	"strings"

	"github.com/codcod/jerry/internal/doc"
)

// EnvelopeSchema versions the machine-readable index. Consumers pin it, so
// changes here are additive only.
const EnvelopeSchema = "jerry.index/1"

// DefaultPath is where the rendered index lives, relative to the repo root.
const DefaultPath = "index/index.md"

// Entry is one row.
type Entry struct {
	ID     string `json:"id,omitempty"`
	Title  string `json:"title"`
	Status string `json:"status"`
	Scope  string `json:"scope"`
	Date   string `json:"date"`
	Path   string `json:"path"`
	Link   string `json:"link"`
}

// Envelope is the JSON form of a whole index.
type Envelope struct {
	Schema string  `json:"schema"`
	ADRs   []Entry `json:"adrs"`
	SDs    []Entry `json:"solution_designs"`
}

// Build collects the entries for a corpus. outputPath is where the index will
// be written; links are made relative to its directory, which is the whole
// reason this takes a path at all — an index at index/index.md that links to
// "teams/..." resolves to "index/teams/..." and every link is broken.
func Build(corpus *doc.Corpus, outputPath string) Envelope {
	envelope := Envelope{Schema: EnvelopeSchema, ADRs: []Entry{}, SDs: []Entry{}}
	base := path.Dir(path.Clean(outputPath))

	for _, document := range corpus.Docs {
		if document.ParseErr != nil {
			continue
		}
		entry := Entry{
			Title:  document.Title(),
			Status: document.StatusLabel(),
			Scope:  document.ScopeLabel(),
			Date:   fallback(document.Front.Date),
			Path:   document.Path,
			Link:   linkFrom(base, document.Path),
		}
		if document.Kind == doc.KindADR {
			entry.ID = fallback(document.Front.ID)
			envelope.ADRs = append(envelope.ADRs, entry)
		} else {
			// Solution designs have no sequential id — the date is the
			// identifier — so there is no ID column to fill with dashes.
			envelope.SDs = append(envelope.SDs, entry)
		}
	}

	sort.SliceStable(envelope.ADRs, func(i, j int) bool {
		if envelope.ADRs[i].Scope != envelope.ADRs[j].Scope {
			return envelope.ADRs[i].Scope < envelope.ADRs[j].Scope
		}
		return envelope.ADRs[i].ID < envelope.ADRs[j].ID
	})
	sort.SliceStable(envelope.SDs, func(i, j int) bool {
		if envelope.SDs[i].Scope != envelope.SDs[j].Scope {
			return envelope.SDs[i].Scope < envelope.SDs[j].Scope
		}
		if envelope.SDs[i].Date != envelope.SDs[j].Date {
			return envelope.SDs[i].Date < envelope.SDs[j].Date
		}
		return envelope.SDs[i].Title < envelope.SDs[j].Title
	})
	return envelope
}

func fallback(value string) string {
	if value == "" {
		return "-"
	}
	return value
}

// linkFrom makes a repo-relative document path relative to the index's own
// directory, climbing out with ".." for each level of nesting.
func linkFrom(base, target string) string {
	if base == "." || base == "" {
		return target
	}
	depth := len(strings.Split(base, "/"))
	return strings.Repeat("../", depth) + target
}

// RenderMarkdown writes the human-facing index.
func RenderMarkdown(w io.Writer, envelope Envelope) error {
	var buf bytes.Buffer
	buf.WriteString("# Index\n\n")
	buf.WriteString("_Auto-generated by `jerry index` — do not edit by hand._\n\n")

	fmt.Fprintf(&buf, "## ADRs (%d)\n\n", len(envelope.ADRs))
	writeTable(&buf, []string{"ID", "Title", "Status", "Scope", "Date"}, rows(envelope.ADRs, true))

	fmt.Fprintf(&buf, "\n## Solution Designs (%d)\n\n", len(envelope.SDs))
	writeTable(&buf, []string{"Title", "Status", "Scope", "Date"}, rows(envelope.SDs, false))

	_, err := w.Write(buf.Bytes())
	return err
}

func rows(entries []Entry, withID bool) [][]string {
	out := make([][]string, 0, len(entries))
	for _, entry := range entries {
		link := fmt.Sprintf("[%s](%s)", escapePipes(entry.Title), entry.Link)
		row := []string{link, escapePipes(entry.Status), escapePipes(entry.Scope), entry.Date}
		if withID {
			row = append([]string{entry.ID}, row...)
		}
		out = append(out, row)
	}
	return out
}

// escapePipes keeps a title containing "|" from splitting its own table row.
func escapePipes(value string) string { return strings.ReplaceAll(value, "|", `\|`) }

func writeTable(buf *bytes.Buffer, headers []string, data [][]string) {
	if len(data) == 0 {
		buf.WriteString("_None yet._\n")
		return
	}
	buf.WriteString("| " + strings.Join(headers, " | ") + " |\n")
	buf.WriteString("|" + strings.Repeat("---|", len(headers)) + "\n")
	for _, row := range data {
		buf.WriteString("| " + strings.Join(row, " | ") + " |\n")
	}
}

// RenderJSON writes the machine-readable index.
func RenderJSON(w io.Writer, envelope Envelope) error {
	encoder := json.NewEncoder(w)
	encoder.SetIndent("", "  ")
	encoder.SetEscapeHTML(false)
	return encoder.Encode(envelope)
}

// Markdown returns the rendered index as a string, for comparison in --check.
func Markdown(envelope Envelope) string {
	var buf bytes.Buffer
	_ = RenderMarkdown(&buf, envelope)
	return buf.String()
}
